Codeunit 50365 "SMTP Test Mail 1"
{
  
  
    trigger OnRun()
VAR
            TempNameValueBuffer : Record 823 TEMPORARY;
            Mail : Codeunit 397;
            AddressChoice : Text;
            ChosenAddress : Option " ","ADMail","BasicAuthMail","UserTableMail","OtherMail";
            Address : Text;
          BEGIN
            Mail.CollectCurrentUserEmailAddresses(TempNameValueBuffer);
            TempNameValueBuffer.RESET;
            IF TempNameValueBuffer.FINDSET THEN
              REPEAT
                IF AddressChoice <> '' THEN
                  AddressChoice := AddressChoice + ',';
                AddressChoice := AddressChoice + TempNameValueBuffer.Value;
              UNTIL TempNameValueBuffer.NEXT = 0;

            AddressChoice := STRSUBSTNO('%1,%2',AddressChoice,TestMailOtherTxt);

            IF AddressChoice = ',' + TestMailOtherTxt THEN
              PromptAndSendEmail
            ELSE BEGIN
              ChosenAddress := STRMENU(AddressChoice,TempNameValueBuffer.COUNT + 1,TestMailChoiceTxt);
              IF ChosenAddress = 0 THEN
                EXIT;
              IF ChosenAddress < TempNameValueBuffer.COUNT + 1 THEN BEGIN
                Address := SELECTSTR(ChosenAddress,AddressChoice);
                SendTestMail(Address);
                MESSAGE(TestMailSuccessMsg,Address);
              END ELSE
                PromptAndSendEmail;
            END;
          END;
    VAR
      TestMailChoiceTxt : TextConst ENU='Choose the email address that should receive a test email message:Option " ","ESP="Elija la direcci�n de correo electr�nico que recibir� un mensaje de correo electr�nico de prueba:';
      TestMailTitleTxt : TextConst ENU='SMTP Test Email MessageOption " ","ESP="Mensaje de correo electr�nico de prueba SMTP';

      TestMailBodyTxt : TextConst ENU='<p style=""font-family:Verdana,Arial;font-size:10pt""><b>This mail message has been generated by the user %1 for test purposes.</b></p><p style=""font-family:Verdana,Arial;font-size:9pt""><b>Sent through SMTP Server:</b> %2<BR><b>SMTP Port:</b> %3<BR><b>Authentication:</b> %4<BR><b>Using Secure Connection:</b> %5<BR><b>Server Instance ID:</b> %6<BR><b>Tenant ID:</b> %7</p>"', ESP='<p style=""font-family:Verdana,Arial;font-size:10pt""><b>El usuario %1 gener� este mensaje de correo electr�nico con fines de prueba.</b></p><p style=""font-family:Verdana,Arial;font-size:9pt""><b>Enviado a trav�s del servidor SMTP:</b> %2<BR><b>Puerto SMTP:</b> %3<BR><b>Autenticaci�n:</b> %4<BR><b>Uso de conexi�n segura:</b> %5<BR><b>Id. de instancia de servidor:</b> %6<BR><b>Id. de suscriptor:</b> %7</p>"';
      TestMailSuccessMsg : TextConst ENU='Test email has been sent to %1.\Check your email for messages to make sure that the email was delivered successfully.Option " ","ESP="Se ha enviado un correo electr�nico de prueba a %1.\Compruebe los mensajes de correo electr�nico para asegurarse de que el correo electr�nico se entreg� correctamente.';
      TestMailOtherTxt : TextConst ENU='Other...Option " ","ESP="Otros...';

    [TryFunction]
    //[Internal]
    PROCEDURE SendTestMail(EmailAddress : Text);
    VAR
      // SMTPMailSetup : Record 409;
      SMTPMail : Codeunit 50355;
      MailManagement : Codeunit 9520;
    BEGIN
      // SMTPMailSetup.GetSetup;

      // SMTPMail.CreateMessage(
      //   '',
      //   MailManagement.GetSenderEmailAddress,
      //   EmailAddress,
      //   TestMailTitleTxt,
      //   STRSUBSTNO(
      //     TestMailBodyTxt,
      //     USERID,
      //     SMTPMailSetup."SMTP Server",
      //     FORMAT(SMTPMailSetup."SMTP Server Port"),
      //     SMTPMailSetup.Authentication,
      //     SMTPMailSetup."Secure Connection",
      //     SERVICEINSTANCEID,
      //     TENANTID),
      //   TRUE);

      SMTPMail.Send;
    END;

    LOCAL PROCEDURE PromptAndSendEmail();
    VAR
      // SMTPUserSpecifiedAddress : Page 410;
      Address : Text;
    BEGIN
      // IF SMTPUserSpecifiedAddress.RUNMODAL = ACTION::OK THEN BEGIN
      //   Address := SMTPUserSpecifiedAddress.GetEmailAddress;
      //   IF Address = '' THEN
      //     EXIT;
      //   SendTestMail(Address);
      //   MESSAGE(TestMailSuccessMsg,Address);
      // END;
    END;

    /* /*BEGIN
END.*/
}







